- name: Demo on First Playbook
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World

- name: demo
  hosts: all
  tasks:
    - name: hello
      ansible.builtin.debug:
        msg: Hi